import { calculateMaturation } from "@/lib/maturation/calculations";
import type {
  AppState,
  Athlete,
  Club,
  Team,
  AnthropometricRecord,
  PerformanceEntry,
} from "@/lib/types";

export const demoClub: Club = {
  id: "club_arenas",
  name: "Arenas Performance Lab",
  region: "Madrid",
};

export const demoTeams: Team[] = [
  { id: "team_u14", clubId: demoClub.id, name: "U14 Boys", ageGroup: "U14" },
  { id: "team_u15g", clubId: demoClub.id, name: "U15 Girls", ageGroup: "U15" },
];

export const demoAthletes: Athlete[] = [
  {
    id: "ath_leo",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
  },
  {
    id: "ath_hugo",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Hugo Sanz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Centre-back",
    dob: "2011-11-02",
  },
  {
    id: "ath_ines",
    clubId: demoClub.id,
    teamId: demoTeams[1].id,
    name: "Ines Vega",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Midfielder",
    dob: "2011-07-22",
  },
  {
    id: "ath_marta",
    clubId: demoClub.id,
    teamId: demoTeams[1].id,
    name: "Marta López",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Forward",
    dob: "2011-05-11",
  },
  {
    id: "ath_diego",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Diego Ruiz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Midfielder",
    dob: "2012-03-02",
  },
  {
    id: "ath_nora",
    clubId: demoClub.id,
    teamId: demoTeams[0].id,
    name: "Nora Blanco",
    sex: "female",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Goalkeeper",
    dob: "2012-06-30",
  },
];

export const demoRecords: AnthropometricRecord[] = [
  {
    id: "rec_1",
    athleteId: "ath_leo",
    athleteName: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
    dataCollectionDate: "2026-03-18",
    statureCm: 157.4,
    bodyMassKg: 46.3,
    sittingHeightCm: 81.5,
    motherHeightCm: 165,
    fatherHeightCm: 178,
    createdAt: "2026-03-18T10:30:00.000Z",
  },
  {
    id: "rec_2",
    athleteId: "ath_hugo",
    athleteName: "Hugo Sanz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Centre-back",
    dob: "2011-11-02",
    dataCollectionDate: "2026-03-18",
    statureCm: 168.9,
    bodyMassKg: 58.2,
    sittingHeightCm: 87.4,
    motherHeightCm: 164,
    fatherHeightCm: 181,
    createdAt: "2026-03-18T10:35:00.000Z",
  },
  {
    id: "rec_3",
    athleteId: "ath_ines",
    athleteName: "Ines Vega",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Midfielder",
    dob: "2011-07-22",
    dataCollectionDate: "2026-03-21",
    statureCm: 162.4,
    bodyMassKg: 51.1,
    sittingHeightCm: 84.2,
    motherHeightCm: 163,
    fatherHeightCm: 176,
    createdAt: "2026-03-21T17:00:00.000Z",
  },
  {
    id: "rec_4",
    athleteId: "ath_leo",
    athleteName: "Leo Martin",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Winger",
    dob: "2012-02-14",
    dataCollectionDate: "2026-01-11",
    statureCm: 154.8,
    bodyMassKg: 44.5,
    sittingHeightCm: 80.2,
    motherHeightCm: 165,
    fatherHeightCm: 178,
    createdAt: "2026-01-11T10:30:00.000Z",
  },
  {
    id: "rec_5",
    athleteId: "ath_marta",
    athleteName: "Marta López",
    sex: "female",
    ageGroup: "U15",
    clubName: demoClub.name,
    teamName: "U15 Girls",
    position: "Forward",
    dob: "2011-05-11",
    dataCollectionDate: "2026-03-22",
    statureCm: 161.0,
    bodyMassKg: 50.4,
    sittingHeightCm: 83.1,
    motherHeightCm: 166,
    fatherHeightCm: 177,
    createdAt: "2026-03-22T09:15:00.000Z",
  },
  {
    id: "rec_6",
    athleteId: "ath_diego",
    athleteName: "Diego Ruiz",
    sex: "male",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Midfielder",
    dob: "2012-03-02",
    dataCollectionDate: "2026-03-17",
    statureCm: 159.2,
    bodyMassKg: 47.8,
    sittingHeightCm: 81.8,
    motherHeightCm: 168,
    fatherHeightCm: 180,
    createdAt: "2026-03-17T10:20:00.000Z",
  },
  {
    id: "rec_7",
    athleteId: "ath_nora",
    athleteName: "Nora Blanco",
    sex: "female",
    ageGroup: "U14",
    clubName: demoClub.name,
    teamName: "U14 Boys",
    position: "Goalkeeper",
    dob: "2012-06-30",
    dataCollectionDate: "2026-03-23",
    statureCm: 154.0,
    bodyMassKg: 44.1,
    sittingHeightCm: 78.9,
    motherHeightCm: 162,
    fatherHeightCm: 175,
    createdAt: "2026-03-23T08:45:00.000Z",
  },
];

export const demoPerformanceEntries: PerformanceEntry[] = [
  {
    id: "perf_1",
    athleteId: "ath_leo",
    athleteName: "Leo Martin",
    area: "physical",
    teamName: "U14 Boys",
    position: "Winger",
    testName: "10 m Sprint",
    unit: "s",
    value: 1.86,
    measurementDate: "2026-03-18",
    notes: "Electronic timing",
    createdAt: "2026-03-18T11:00:00.000Z",
  },
  {
    id: "perf_2",
    athleteId: "ath_hugo",
    athleteName: "Hugo Sanz",
    area: "technicalTactical",
    teamName: "U14 Boys",
    position: "Centre-back",
    testName: "Video Tactical Decisions",
    unit: "/10",
    value: 7.8,
    measurementDate: "2026-03-19",
    notes: "Coach panel rating",
    createdAt: "2026-03-19T11:00:00.000Z",
  },
  {
    id: "perf_3",
    athleteId: "ath_ines",
    athleteName: "Ines Vega",
    area: "psychological",
    teamName: "U15 Girls",
    position: "Midfielder",
    testName: "Confidence Score",
    unit: "/10",
    value: 8.4,
    measurementDate: "2026-03-21",
    notes: "Self-report",
    createdAt: "2026-03-21T18:00:00.000Z",
  },
  {
    id: "perf_4",
    athleteId: "ath_marta",
    athleteName: "Marta López",
    area: "physical",
    teamName: "U15 Girls",
    position: "Forward",
    testName: "CMJ",
    unit: "cm",
    value: 29.3,
    measurementDate: "2026-03-22",
    notes: "Single-leg jump",
    createdAt: "2026-03-22T09:45:00.000Z",
  },
  {
    id: "perf_5",
    athleteId: "ath_diego",
    athleteName: "Diego Ruiz",
    area: "technicalTactical",
    teamName: "U14 Boys",
    position: "Midfielder",
    testName: "Passing Accuracy",
    unit: "%",
    value: 87.5,
    measurementDate: "2026-03-17",
    notes: "10 passes target drill",
    createdAt: "2026-03-17T11:10:00.000Z",
  },
  {
    id: "perf_6",
    athleteId: "ath_nora",
    athleteName: "Nora Blanco",
    area: "psychological",
    teamName: "U14 Boys",
    position: "Goalkeeper",
    testName: "Coachability Rating",
    unit: "/10",
    value: 9.0,
    measurementDate: "2026-03-23",
    notes: "Muy receptiva",
    createdAt: "2026-03-23T09:00:00.000Z",
  },
];

export const demoState: AppState = {
  club: demoClub,
  teams: demoTeams,
  athletes: demoAthletes,
  records: demoRecords,
  performanceEntries: demoPerformanceEntries,
  trainingLoadEntries: [],
  performanceDefinitions: [
    // Physical tests
    { id: "pdef-10m-sprint", name: "10 m Sprint", area: "physical", unit: "s", attempts: 1, isRating: false, calculation: "best_min", description: "Velocidad en sprint corto, mide la aceleracion inicial." },
    { id: "pdef-cmj", name: "CMJ", area: "physical", unit: "cm", attempts: 1, isRating: false, calculation: "best_max", description: "Counter Movement Jump, mide la potencia explosiva de las piernas." },
    { id: "pdef-yoyo", name: "Yo-Yo IR1", area: "physical", unit: "m", attempts: 1, isRating: false, calculation: "best_max", description: "Test de resistencia intermitente, evalua la capacidad aerobica." },
    { id: "pdef-505", name: "505 COD", area: "physical", unit: "s", attempts: 1, isRating: false, calculation: "best_min", description: "Change of Direction test, mide la agilidad y cambio de direccion." },
    { id: "pdef-wall-sit", name: "Wall Sit Test", area: "physical", unit: "s", attempts: 1, isRating: false, calculation: "best_max", description: "Test de resistencia isometrica, mide el tiempo que se mantiene la posicion." },
    // Technical-Tactical tests
    { id: "pdef-passing", name: "Passing Accuracy", area: "technicalTactical", unit: "%", attempts: 1, isRating: false, calculation: "average", description: "Precision en pases, mide la tecnica de pase." },
    { id: "pdef-dribbling", name: "Dribbling Slalom", area: "technicalTactical", unit: "s", attempts: 1, isRating: false, calculation: "best_min", description: "Tiempo en slalom con balon, evalua el control y velocidad." },
    { id: "pdef-video-decision", name: "Video Tactical Decisions", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Evaluacion de decisiones tacticas en video." },
    { id: "pdef-ssg-decision", name: "Small-Sided Decision Rating", area: "technicalTactical", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Calificacion en partidos reducidos." },
    // Psychological tests
    { id: "pdef-confidence", name: "Confidence Score", area: "psychological", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Nivel de confianza del jugador." },
    { id: "pdef-motivation", name: "Motivation Score", area: "psychological", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Motivacion intrinseca." },
    { id: "pdef-anxiety", name: "Competitive Anxiety", area: "psychological", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Ansiedad competitiva." },
    { id: "pdef-coachability", name: "Coachability Rating", area: "psychological", unit: "/10", attempts: 1, isRating: true, calculation: "average", description: "Capacidad de aprendizaje." },
  ],
  preferences: {
    locale: "es",
  },
};

export const demoAssessments = demoRecords.map(calculateMaturation);
